### PR TITLE
Detect Facebook In-App Browsers without versions

### LINKED ISSUE #421: unrecognize facebook app for ios
My facebook app user-agent string:

Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,3;FBMD/iPhone;FBSN/iOS;FBSV/13.0;FBSS/3;FBID/phone;FBLC/zh_CN;FBOP/5;FBCR/中-国-联-通-]

`/;fbav\/([\w\.]+);/i` can not detect it.

### PR DESCRIPTION
**Pull request by nionata**
fixes #421 

The current regex expression for Facebook In-App Browsers does not catch the newer iOS apps. Their User-Agents are being sent without versions, so they are not being detected as the current expression only looks for FBAV (Facebook App Version). 
> [Here](https://user-agents.net/applications/facebook-app/platforms/ios) you can see most of latest the iOS User-Agents are not being sent with versions

The new regex expression will serve as a **backup** to detect Facebook Browsers if a version is not included in the User-Agent. If FBAV is present, the original regex will be used.
> The expression match is based on [Facebook Best Practices](https://developers.facebook.com/docs/sharing/best-practices#crawl)
"Check for a HTTP User-Agent with the value FB_IAB/FB4A for Android and FBAN/FBIOS for iOS."

### CODE REVIEW

**Comment by nionata** [comment]
@faisalman thoughts?

**Comment by elad-yosifon** [comment]
@faisalman any news?

**Comment by nionata** [comment]
Here is a temporary fix until this gets merged in @elad-yosifon 
``` javascript
const facebookNoVersion = [[/FBAN\/FBIOS|FB_IAB\/FB4A/i], [[UAParser.BROWSER.NAME, 'Facebook']]] 
let parser = new UAParser(ua, { browser: facebookNoVersion })
```

**Comment by faisalman** [comment]
Merged. Thanks 👍

**Pull request merged**
