### PR TITLE
Added a script to bump version in project files

### LINKED ISSUE #107: bump version script required
How do you update version number in all files when version changes?
Do you have a special script for that? If not, I can create one to automate the process.

### PR DESCRIPTION
**Pull request by duzun**
Ussage:

`npm run verup` - increment revision by 1
`npm run verup 2` - increment revision by 2
`npm run verup 1.0` - increment minor version by 1
`npm run verup -- 1.0.0` - increment major version by 1
`npm run verup -- -1` - decrement revision by 1

Close #107.

P.S. The script uses `JSON.stringify` for .json files, thus the diff in those files.

### CODE REVIEW

**Comment by tracker1** [comment]
@duzun npm already has this functionality built in... `npm version (major|minor|patch)`

[for example see publish-* script commands here](https://github.com/tracker1/mssql-ng/blob/master/package.json) with this in place, I can `npm run publish-patch` which will build my project (creating an es5 `dist/` directory), publish to npm, and push the tag to github.

**Comment by duzun** [comment]
@tracker1 I'm well aware of npm's version bumper command. But it doesn't touch any other file but `package.json`.
My script reads `version` field from `package.json`, changes version if needed, then patches other project files with this new version.

**Comment by tracker1** [comment]
Wild, didn't realize... in that case, you may want to run a github tag against the new version after the files are safed, so each version can get pushed into git/github.  I'm only using npm these days.

**Comment by duzun** [comment]
I have created a repo for [`verup`](https://github.com/duzun/verup) script and intend to update it here as soon as I have any interesting change.

Cheers

**Comment by faisalman** [comment]
Thanks for the script @duzun , just tried it out and feels like.. magic! :+1:

**Comment by duzun** [comment]
Thanks for `ua-parser` :-)

**Pull request merged**
