### PR TITLE
Restore commented devices

### PR DESCRIPTION
**Pull request by JMDidon**
This devices had been added but commented out. As I think those devices are useful and that adding them wasn't causing any problem in the actual detection, I thought we could add them again.

### CODE REVIEW

**Comment by bcaudan** [comment]
+1

I also need to detect these devices correctly!

**Comment by otakusid** [comment]
+1

**Comment by loris** [comment]
@faisalman Do you need something else to merge this one? more tests? Right now the library misidentifies any new Samsung phones.

**Comment by faisalman** [comment]
I prefer to restore these devices to a string map.. Closing this for now

**Pull request closed without merging**
