### PR TITLE
feat: add Klarna Shopping Browser UA parser

### PR DESCRIPTION
**Pull request by darasus**
Klarna App with 150 million users is rather popular shopping browser.

Adding support for Klarna UA parser.

### CODE REVIEW

**Review by faisalman — CHANGES_REQUESTED** [review]
The detection for Apps that's not primarily used as a browser will be migrated here forward:

https://github.com/faisalman/ua-parser-js/blob/master/src/extensions/ua-parser-extensions.js#L20

**Comment by darasus** [comment]
Hey @faisalman, thanks for merging this PR! Is this going to v1 or v2?

**Comment by faisalman** [comment]
v2, but might as well backported to v1 later

**Comment by darasus** [comment]
@faisalman how can we add this to v1?

**Comment by faisalman** [comment]
In the mean time, you can pass it as an extension when instantiating UAParser

```js
const browsers = [
    [/(klarna)\/([\w\.]+)/i], [UAParser.BROWSER.NAME, UAParser.BROWSER.VERSION]
];
const parser = new UAParser({ browser: browsers });

const ua = 'Mozilla/5.0 (Linux; Android 12; moto g(60)s Build/S3RLS32.114-25-13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 Klarna/23.36.215';

uap.setUA(ua).getBrowser(); // { name: 'Klarna', version: '23.36.215', major: '23'} 

```

More details at https://docs.uaparser.js.org/v2/intro/extending-regex.html

**Pull request merged**
