### PR TITLE
Mac OS rebranded to macOS as of Sierra

### PR DESCRIPTION
**Pull request by valeriansaliou**
See:

* http://www.theverge.com/2016/6/8/11891626/apple-rebrand-os-x-mac-os-evidence-mounts

Apple source:

* http://www.apple.com/macos/sierra/

FYI, I consider all previous Mac OS version to be rebranded to macOS too. Let me know if I should apply a per-version detection, ie. detect if macOS version < 10.12 and call it Mac OS, else call it macOS.

### CODE REVIEW

**Comment by astorije** [comment]
Does this have a chance to be merged?

@valeriansaliou, you have a failing test since there needs to be a `Mac OS` renaming there as well.

**Comment by valeriansaliou** [comment]
Done, fixed tests 👍

**Comment by Seldaek** [comment]
This breaks backwards compatibility with anyone checking for the "Mac OS", in a pretty nasty and hard to spot way.. I don't think it's a good idea.

**Comment by valeriansaliou** [comment]
Then I guess it would be a better idea to only include this change in a MAJOR semver release

**Comment by astorije** [comment]
Since this project is still a `0.x`, then bumping the minor (to `0.8`) is appropriate for a breaking change :)

**Comment by erikgaal** [comment]
What's the status on this PR?

**Review by 33Crypto — APPROVED** [review]
#Reviewed
#Commit
#Create
{XML}

**Comment by 33Crypto** [comment]
#LOCK33Creator>o(tab)

**Pull request closed without merging**
