### PR TITLE
Fix license

### PR DESCRIPTION
**Pull request by evaliyev**
I've noticed that license that you declared in `license.md` does not match licenses declared in `package.json` and `readme.md`. 

Since licenses in `package.json` and `readme.me` are much older (3 and 2 years old) than `license.md` (8 months), I assumed that your intention was to keep MIT license. 

Keeping GPL and MIT at the same time is quite confusing.

### CODE REVIEW

**Comment by evaliyev** [comment]
@faisalman @mralbean @vladimyr  Please take a look

**Comment by vladimyr** [comment]
FWIW You have my 👍

**Comment by evaliyev** [comment]
Thanks!
If this PR is approved, please don't forget to merge it :)

**Comment by vladimyr** [comment]
> If this PR is approved, please don't forget to merge it :)

Well, I don't have write access 🙃

**Pull request merged**
